### ISSUE TITLE
Consistency between learning units 

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/instructors-forum#4]
**_Motivation:_** 
Our learning units were made by different people, and while most of the times that is not an issue, occasionally there are significant differences. 

**_Note:_** This Issue is about structure and consistency of learning units (more high level). For low level discussion about the learning units content, please use [Issue 8](https://github.com/LDSSA/instructors-forum/issues/8)

**_Examples:_**
- Some learning units have well-structured exercises, while others have the instructions in the README 
- Some learning units have many comments explaining code, while others assume the students just heard the lecture 
- Some folders have images mixed with notebooks, instead of having the images in the data folders 
- Some learning units have multiple example notebooks instead of 1 
- Some learning units use numpy instead of pandas to prepare datasets 

**_Proposed solution:_** 
1. go through all the learning units and present proposals for increasing uniformity. In cases where it is trivial (e.g. putting images in folders) he will simply do so directly.
2. establish a table or graph of precedents, to help us understand what topics need to be understood before others can be taught.
3. Add the learning units that are part of the hackathons to the formal curriculum. There will probably end up being around 25 learning units, some of which will be multi-week (probably broken into sub-folders, 1 per week) 
4. Re-consider the order of the learning units  

**_TODO LIST:_** 
- [x] Read all learning units and present [list of structure improvements](https://docs.google.com/spreadsheets/u/3/d/14XVv6vx0NicWEGeYEE-rhLSxrqeevqTadP_NgbBUF70/edit?usp=sharing) (Pedro)
- [ ] Establish the table / graph of [precedents](https://docs.google.com/document/d/1URoo8KZhDh6xnIoqLxzvhgCRG5fEjGSNVWmDr0DixNk/edit#heading=h.tt47dde4bdce) 
- [ ] Re-think order and / or topics 
- [ ] Update guidelines for instructors to build Learning Units 
- [ ] Add hackathon learning units to curriculum

**Comment by jtascensao** [comment]
We also have an opportunity to improve the actual content of the units, I assume that's out of the scope of this thread?

**Comment by PedroGFonseca** [comment]
@jtascensao technically yes, but I am doing both at the same time. I'll start a separate thread for content quality

**Comment by hershaw** [comment]
Are @PedroGFonseca and @jtascensao taking lead on this one? Should we assign the issue to one of you guys?
