### ISSUE TITLE
Improve content of learning units 

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/instructors-forum#8]
We now have a (pretty good) baseline of learning units to work with, but that shouldn't make us complacent. 

There should be a thorough review of all learning units, and suggestions for content improvement. 

This can include, but is not limited to: 
- Clarity of explanations 
- Quality of slides 
- Choice of examples and exercises 
- Choice of datasets 
- Choice of implementations 
- Typos 
- Scope bloat
- Missing points 

(_Note: for the structure of the learning units and choice of curriculum, please use [Issue 4 instead](https://github.com/LDSSA/instructors-forum/issues/4)_)

As an action, I propose that issues be opened for every learning unit with proposals for improvements. 
These should be handled primarily by the original creator, but if the person is not available Pedro will assign instructors to "orphan" learning units. 

**_TODO:_** 
- [X] Read all learning units 
- [X] Make lists of recommendations for each of them 
- [ ] Open individual issues for each with the recommendations 
- [ ] Try to get the original author to make improvements, and add their own before next Academy
- [ ] It previous step not successful, assign instructors to improve learning units

**Comment by PedroGFonseca** [comment]
@jtascensao I'm currently working on this [here](https://docs.google.com/spreadsheets/d/14XVv6vx0NicWEGeYEE-rhLSxrqeevqTadP_NgbBUF70/edit?usp=sharing), would be great to have more eyes on this!

**Comment by jtascensao** [comment]
@PedroGFonseca I'm happy to join you on this, already requested for access.

**Comment by PedroGFonseca** [comment]
Adding the full (current) curriculum [here](https://docs.google.com/document/d/1URoo8KZhDh6xnIoqLxzvhgCRG5fEjGSNVWmDr0DixNk/edit#heading=h.tt47dde4bdce)

**Comment by jtascensao** [comment]
@PedroGFonseca there's at least one unit I think we should consider adding: Advanced SciPy, with vectorization in NumPy, sparse matrices, etc., and a quick overview of linear algebra in Python. 

I'm ok with taking on that unit if the team thinks it's added value.

**Comment by PedroGFonseca** [comment]
I think we should, yes. It was one of the major bottlenecks for students, and we should teach it explicitly.

**Comment by jtascensao** [comment]
I think it should be one of the first lessons, as some of the transformers that we cover, for example, return sparse matrices by default. What's the process of adjusting the curriculum?

**Comment by HugoDLopes** [comment]
@PedroGFonseca I have some nice notebooks on Data Visualization that we can use to improve the module on that topic.

**Comment by jtascensao** [comment]
@HugoDLopes thank god! 😄

**Comment by jtascensao** [comment]
@PedroGFonseca had some time today, already included some notes in the spreadsheet. Will continue.

**Comment by PedroGFonseca** [comment]
@jtascensao excellent, when we're done we should turn these into separate github issues for each LU, and assign people to fix them. Then we'll have to share the "unfixed" ones. (sorry for the duplication with Trello, still trying to figure out what goes where)

**Comment by jtascensao** [comment]
@PedroGFonseca I'm about halfway through, if you have some time to check out my notes and share some feedback, that would be great so I can adjust. If not, no worries, I'll keep going.

**Comment by PedroGFonseca** [comment]
I've checked them and they seem to be spot on so far.

**Comment by jtascensao** [comment]
@PedroGFonseca just finished reviewing the units! A few suggestions:

* We could include a learning unit on feature selection (we never address it)
* We could include a learning unit on regressors
* We could include a learning unit on validation metrics for regression
* We could include a learning unit on stats, suggested topics (recurrent in units):
    * Most common probability distributions
    * Confidence intervals
    * Hypothesis testing
* We could consider including a unit on advanced SciPy, albeit perhaps not the most critical
* We should mention binning, my suggestion is including it in `Unit 14 - Working with real data`

Detailed notes on each unit in the [spreadsheet](https://docs.google.com/spreadsheets/d/14XVv6vx0NicWEGeYEE-rhLSxrqeevqTadP_NgbBUF70/edit?ts=5a6e1c92#gid=1033220472).
